[package]
name = "torifune"
version = "0.1.0"
authors = ["Akihiro Takai <at.sisy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
nalgebra = "0.18.1"
